### ISSUE TITLE
get css hot reloading working

### ISSUE THREAD

**Issue by nickm-scribestar** [nickmeldrum/sticky-board#4]

**Comment by nickmeldrum** [comment]
or use webpack or something?

**Comment by nickmeldrum** [comment]
using browsersync?

**Comment by nickmeldrum** [comment]
i think browsersync + react-hot-loader is a little complex at the moment, look at these for more details:
https://github.com/gaearon/react-hot-loader/issues/176
https://github.com/gajus/react-css-modules/issues/51

so for now I am going to use the more "webpacky" way of doing it using css-modules - i just don't love it as it's using js to load in css which isn't the way the browsers like it and is suboptimal in terms of efficiency of css loading...

**Comment by nickmeldrum** [comment]
for now fixed with commit: 3a711021d8ebc61dbcb9c0e2cc758825bd05f6fe
